src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Repository\RecetteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: RecetteRepository::class)]
#[Vich\Uploadable]

class Recette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    public ?string $Name = null;

    #[ORM\Column(length: 500)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Time = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255, nullable: false)]
    private ?string $file = null;

    #[Vich\UploadableField(mapping: 'recette_images', fileNameProperty: 'file')]
    private ?File $imageFile = null;

    #[Assert\Range(min: 1, max: 3)]
    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\OneToMany(mappedBy: 'recette', targetEntity: Commentaire::class, cascade: ['persist', 'remove'])]
    private Collection $commentaires;

    #[ORM\Column(nullable: true)]
    private ?float $noteMoyenne = null;




    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->commentaires = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->Name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }


    public function getTime(): ?\DateTimeInterface
    {
        return $this->Time;
    }

    public function getToStringTime(): ?string
    {
        return $this->Time->format("H:i");
    }

    public function setTime(\DateTimeInterface $Time): self
    {
        $this->Time = $Time;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $time): self
    {
        $this->createdAt = $time ;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @throws \Exception
     */
    public function setImageFile(?File $file): self
    {
        $this->imageFile = $file;
        if ($file) {
            $this->createdAt = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        }
        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setRecette($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getRecette() === $this) {
                $commentaire->setRecette(null);
            }
        }

        return $this;
    }

    public function getNoteMoyenne(): ?float
    {
        return $this->noteMoyenne;
    }

    public function setNoteMoyenne(): self
    {
        $this->noteMoyenne = 0;
        $liste = $this->getCommentaires();
        foreach ($liste as $commentaire) {
            $this->noteMoyenne += $commentaire->getNote();
        }
        $this->noteMoyenne = $this->noteMoyenne / (count($liste)>0? count($liste):1);

        return $this;
    }


}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\RecetteRepository;
use App\Service\SearchService;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(PaginatorInterface $paginator,Request $request,RecetteRepository $recetteRepository, SearchService $searchService): Response
    {
        $recettesAll = $recetteRepository->findBy([], ['noteMoyenne' => 'DESC']);

        foreach ($recettesAll as $recettes) {
                $recettes->setNoteMoyenne();
                $recetteRepository->save($recettes, true);
        }

        if($request->isMethod('POST') && $request->request->get('Research') != null) {
            $articles = $searchService->search($recetteRepository, $request);

            return $this->render('recette/index.html.twig', [
                'recettesNav' =>  $recetteRepository->findAll(),
                'recettes'=> $articles,
            ]);
        }

        return $this->render('home/index.html.twig', [
            'recettesNav' => $recettesAll,
        ]);
    }


}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    <body class=" h-screen font-semibold " style="background-color: rgb(251,244,232)" >

        <main class="  h-full w-full">
            <section class=" h-1/3 " style="background-color: rgb(47,82,70)">
                <div class="h-full w-full  flex flex-col align-middle justify-evenly items-center">
                    <p class="text-3xl text-white">Bienvenue sur mon blog recette {{ app.user }}</p>
                    <div class="flex justify-center items-center ">
                        <a class="flex items-center " style="background-color: rgb(47,82,70)" href="{{ path('app_recette_index') }}">
                            <p class="text-2xl  text-white mr-2 hover:underline" >Toute les recettes</p>
                            <i class="fas fa-arrow-right text-3xl font-bold text-white "></i>
                        </a>
                    </div>
                </div>
            </section>

            <section class="py-8">
                <div class="flex justify-center ">
                    <p class="text-3xl font-bold text-gray-800 mb-8">Top Recettes</p>
                </div>
                    <div class="w-full h-full m-auto flex flex-wrap justify-evenly ">
                        {%  for recette in recettesNav|slice(0,3) %}
                            <div class="w-1/4 h-full ">
                                    <a class="w-full " href="{{ path('app_recette_show', {'id': recette.id}) }}">
                                        <div class="w-full h-64 bg-cover bg-center rounded-t " style="background-image: url({{ vich_uploader_asset(recette, recette.imageFile) }})" > </div>
                                    </a>
                                    <div class="px-6 py-4">
                                        <div class="mb-2 text-xl font-bold text-gray-800 flex">
                                            <p class="mr-2">{{ recette.name }}</p>
                                            <div>
                                                {% for i in range(0,recette.prix-1) %}
                                                    <i class="fas fa-euro-sign text-red-500"></i>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <p class="text-base text-gray-700">Temps : {{ recette.toStringTime }} H</p>
                                        <p class="text-base text-gray-700">{{ recette.description }}.</p>
                                        <div class="flex items-center" id="list-star">
                                                {% for i in 1..5 %}
                                                    {% if recette.noteMoyenne >= i %}
                                                        <i class="fas fa-star text-red-500"></i>
                                                    {% else %}
                                                        <i class="far fa-star text-red-500"></i>
                                                    {% endif %}
                                                {% endfor %}
                                                <p class="ml-2.5">({{ recette.commentaires.count }} avis)</p>
                                        </div>
                                    </div>
                                </div>
                        {% endfor %}
                    </div>
            </section>

        </main>

    </body>

{% endblock %}