src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Repository\RecetteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: RecetteRepository::class)]
#[Vich\Uploadable]

class Recette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    public ?string $Name = null;

    #[ORM\Column(length: 500)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Time = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255, nullable: false)]
    private ?string $file = null;

    #[Vich\UploadableField(mapping: 'recette_images', fileNameProperty: 'file')]
    private ?File $imageFile = null;

    #[Assert\Range(min: 1, max: 3)]
    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\OneToMany(mappedBy: 'recette', targetEntity: Commentaire::class, cascade: ['persist', 'remove'])]
    private Collection $commentaires;

    #[ORM\Column(nullable: true)]
    private ?float $noteMoyenne = null;




    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->commentaires = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->Name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }


    public function getTime(): ?\DateTimeInterface
    {
        return $this->Time;
    }

    public function getToStringTime(): ?string
    {
        return $this->Time->format("H:i");
    }

    public function setTime(\DateTimeInterface $Time): self
    {
        $this->Time = $Time;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $time): self
    {
        $this->createdAt = $time ;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @throws \Exception
     */
    public function setImageFile(?File $file): self
    {
        $this->imageFile = $file;
        if ($file) {
            $this->createdAt = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        }
        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setRecette($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getRecette() === $this) {
                $commentaire->setRecette(null);
            }
        }

        return $this;
    }

    public function getNoteMoyenne(): ?float
    {
        return $this->noteMoyenne;
    }

    public function setNoteMoyenne(): self
    {
        $this->noteMoyenne = 0;
        $liste = $this->getCommentaires();
        foreach ($liste as $commentaire) {
            $this->noteMoyenne += $commentaire->getNote();
        }
        $this->noteMoyenne = $this->noteMoyenne / (count($liste)>0? count($liste):1);

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\Email]
    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 255 )]
    private ?string $Username = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commentaire::class, cascade: ['persist', 'remove'])]
    private Collection $commentaires;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->commentaires = new ArrayCollection();
        //a enlever après la création du premier user
        $this->roles = ['ROLE_ADMIN'];
    }

    public function __toString(): string
    {
        return (string) $this->getUsername();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->id;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setUser($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUser() === $this) {
                $commentaire->setUser(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Form/RecetteType.php
<?php

namespace App\Form;

use App\Entity\Recette;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecetteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name')
            ->add('Description')
            ->add('Time')
            ->add('file')
            ->add('prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recette::class,
        ]);
    }
}

src/Controller/RecetteController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Recette;
use App\Form\RecetteType;
use App\Repository\CommentaireRepository;
use App\Repository\RecetteRepository;
use App\Service\SearchService;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\CommentaireType;


#[Route('/recette')]
class RecetteController extends AbstractController
{


    #[Route('/', name: 'app_recette_index', methods: ['GET', 'POST'])]
    public function index(RecetteRepository $recetteRepository, Request $request, SearchService $searchService): Response
    {
        $articles = $recetteRepository->findBy([], ['noteMoyenne' => 'DESC']);
        if($request->isMethod('POST') && $request->request->get('Research') != null) {
            $articles = $searchService->search($recetteRepository, $request);
            return $this->render('recette/index.html.twig', [
                'recettesNav' =>  $recetteRepository->findAll(),
                'recettes'=> $articles ,
            ]);
        }

        return $this->render('recette/index.html.twig', [
            'recettesNav' => $recetteRepository->findAll(),
            'recettes' => $articles,
        ]);
    }

    #[Route('/new', name: 'app_recette_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RecetteRepository $recetteRepository): Response
    {
        $recette = new Recette();
        $form = $this->createForm(RecetteType::class, $recette);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recetteRepository->save($recette, true);

            return $this->redirectToRoute('app_recette_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recette/new.html.twig', [
            'recette' => $recette,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recette_show', methods: ['GET', 'POST'])]
    public function show(Recette $recette, Request $request,RecetteRepository $recetteRepository, CommentaireRepository $commentaireRepository, SearchService $searchService): Response
    {
        if($request->isMethod('POST') && $request->request->get('Research') != null) {
            $articles = $searchService->search($recetteRepository, $request);
            return $this->render('recette/index.html.twig', [
                'recettesNav' =>  $recetteRepository->findAll(),
                'recettes'=> $articles,
            ]);
        }
        $recettes_navbar = $recetteRepository->findAll();
        $commentaires = $commentaireRepository->findBy(['recette' => $recette]);
        $test = $this->getUser();
        $commentaire = new Commentaire();
        $commentaire->setRecette($recette);
        $commentaire->setUser($this->getUser());
        $commentaire->setCreatedAt(new \DateTime());
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentaireRepository->save($commentaire, true);
            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('recette/show.html.twig', [
            'recette' => $recette,
            'user' => $test,
            'recettesNav' => $recettes_navbar,
            'form' => $form->createView(),
            'commentaire' => $commentaire,
            'commentaires' => $commentaires,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_recette_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Recette $recette, RecetteRepository $recetteRepository): Response
    {
        $form = $this->createForm(RecetteType::class, $recette);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recetteRepository->save($recette, true);

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recette/edit.html.twig', [
            'recette' => $recette,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recette_delete', methods: ['POST'])]
    public function delete(Request $request, Recette $recette, RecetteRepository $recetteRepository, CommentaireRepository $commentaireRepository): Response
    {
        $recetteRepository->remove($recette, true);

        return $this->redirectToRoute('app_recette_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/recette/_delete_form.html.twig
<form method="post" action="{{ path('app_recette_delete', {'id': recette.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recette.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recette/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/recette/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recette{% endblock %}

{% block body %}
    <h1>Edit Recette</h1>

    {{ include('recette/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_recette_index') }}">back to list</a>

    {{ include('recette/_delete_form.html.twig') }}
{% endblock %}

templates/recette/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recette index{% endblock %}

{% block body %}
    <body class="relative h-screen w-screen font-semibold " style="background-color: rgb(251,244,232)">
        <main class="h-full w-screen flex justify-center pt-4">
            <section class="mt-4 h-full w-3/5 flex justify-center">
                <div class="w-3/4 h-full flex flex-col items-center ">
                    <div class="flex flex-col justify-center items-center mb-1">
                        <h1 class="text-4xl font-bold text-center text-gray-800">Recettes</h1>
                    </div>
                    {% for recette in recettes %}
                        <div class="flex flex-row justify-between items-center w-full h-2/6 border-b-2 border-gray-300">
                            <div class="w-full h-64 bg-cover bg-center rounded-t " style="background-image: url({{ vich_uploader_asset(recette, recette.imageFile) }})" > </div>
                            <div class="flex flex-row justify-evenly items-center w-2/3 h-full ">
                                <div class="flex flex-col justify-evenly w-3/4 h-full ">
                                    <h2 class="text-2xl font-bold text-gray-800">
                                        {{ recette.name }}
                                    </h2>
                                    <div class="flex items-center" id="list-star">
                                        {% for i in 1..5 %}
                                            {% if recette.noteMoyenne >= i %}
                                                <i class="fas fa-star text-red-500"></i>
                                            {% else %}
                                                <i class="far fa-star text-red-500"></i>
                                            {% endif %}
                                        {% endfor %}
                                        <p class="ml-2.5">({{ recette.commentaires.count }} avis)</p>
                                    </div>
                                    <p class="underline">publié le {{ recette.createdAt.format("j/m/y") }}</p>
                                </div>
                            </div>
                            <div class="flex flex-row justify-center items-center w-1/3 h-full">
                                <a href="{{ path('app_recette_show', {'id': recette.id}) }}" class="text-gray-800 text-center text-xl font-bold w-1/2 h-3/4 flex justify-center items-center rounded-md">Voir</a>

                            </div>
                        </div>
                    {% else %}
                        <div class="flex flex-col justify-center items-center w-full h-screen">
                            <h2 class="text-2xl font-bold text-gray-800">Aucune recette</h2>
                        </div>
                    {% endfor %}
                    <div class="inline-flex items-center -space-x-px">
                    </div>
                </div>
            </section>
        </main>
    </body>


{% endblock %}

templates/recette/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recette{% endblock %}

{% block body %}
    <h1>Create new Recette</h1>

    {{ include('recette/_form.html.twig') }}

    <a href="{{ path('app_recette_index') }}">back to list</a>
{% endblock %}

templates/recette/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recette{% endblock %}

{% block body %}
    <body class="relative h-screen font-semibold " style="background-color: rgb(251,244,232)">
        <div id="window" class="absolute h-full w-full flex justify-center items-center hidden ">
            <div class="w-1/2 h-1/2 bg-white overflow-scroll rounded fixed border-8 border-black">
                <div class="px-2 flex justify-between my-1 border-b-4 border-black">
                    <p>Commentaires ({{ recette.commentaires.count }})</p>
                    <button type="button" class="border border-black rounded-2xl px-2" onclick="document.getElementById('window').style.display = 'none'"><i class="fa fa-xmark"></i></button>
                </div>
                <div class="m-4 w-auto h-auto flex flex-col">
                    {% for commentaire in recette.commentaires %}
                    <div class="w-full border-b border-black flex justify-between">
                        <div>
                        <p>@{{ commentaire.user.username }}</p>
                        <p>{{ commentaire.contenue }}</p>
                            {% for i in 1..5 %}
                                {% if commentaire.note >= i %}
                                    <i class="fas fa-star text-red-500"></i>
                                {% else %}
                                    <i class="far fa-star text-red-500"></i>
                                {% endif %}
                            {% endfor %}
                            <p>Le {{ commentaire.createdAt | date('d/m/Y') }} à {{ commentaire.createdAt | date('H:i') }}</p>

                        </div>
                        <div>
                            {% if commentaire.user == app.user %}
                                <div class=" flex items-center text-red-500 ">
                                    <i class="fa-solid fa-trash pr-2"></i>
                                    {{ include('commentaire/_delete_form.html.twig') }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>
        <main onclick="" class=" h-full  w-full">
            <div class="w-4/5 h-4/5 m-auto mt-4">
                <section class="container m-auto h-4/5 p-4 shadow-xl">
                    <h1 class="text-4xl text-center font-bold text-gray-800 pb-4 p-4 border-b border-black">{{ recette.name }}</h1>
                    <div class="h-3/4 flex items-center w-full h-full">
                        <span class="w-1/3 h-1/2 bg-cover  rounded-t " style="background-image: url({{ vich_uploader_asset(recette, recette.imageFile) }})"></span>
                        <div class="w-2/3 h-1/2 flex flex-col p-2">
                            <p class="m-auto">Description :</p>
                            <p class="m-auto">{{ recette.description }}</p>
                            <div class="m-auto">
                                Cout :
                                {% for i in range(0,recette.prix-1) %}
                                    <i class="fas fa-euro-sign text-red-500"></i>
                                {% endfor %}
                            </div>
                            <p class="m-auto">Temps : {{ recette.createdAt | date('H') }}H{{ recette.createdAt | date('i') }}</p>
                        </div>
                    </div>
                </section>
                <section class="h-2/5 mt-4 flex flex-col ">
                    <div class="h-2/3 w-full flex flex-col justify-center border border-black">
                            {{ include('commentaire/_form.html.twig') }}
                    </div>
                    <div class="h-1/3  flex items-center justify-center align-middle">
                        {% if recette.commentaires.count == 0  %}
                        <button class="border border-black rounded-2xl p-2 bg-red-600 shadow-xl">Pas de commentaires</button>
                        {% else %}
                        <button class="border border-black rounded-2xl p-2 bg-red-500 shadow-xl" onclick="document.getElementById('window').style.display ='flex'">Voir les Commentaires ({{ recette.commentaires.count }})</button>
                        {% endif %}
                    </div>
                </section>
            </div>
        </main>
    </body>

{% endblock %}